[versions]
agp = "9.0.1"
maven-publish = "0.36.0"
raung = "0.1.1"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
raung-asm = { module = "io.github.skylot:raung-asm", version.ref = "raung" }

[plugins]
java-gradle-plugin = { id = 'java-gradle-plugin' }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

